server {
    listen 80;
    listen [::]:80;

    server_name s8.localhost;

    index   index.php;
    charset utf-8;

    location / {
        proxy_pass http://php8.4-fpm:9001;

        # 设置请求头，确保 Hyperf 能获取到真实的客户端 IP 和域名
        proxy_set_header Host              $http_host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
server {
    listen 80;
    listen [::]:80;

    server_name s7.localhost;

    index   index.php;
    charset utf-8;

    location / {
        proxy_pass http://php7.2-fpm:9001;

        # 设置请求头，确保 Hyperf 能获取到真实的客户端 IP 和域名
        proxy_set_header Host              $http_host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}