server {
    listen 80;
    listen [::]:80;
    server_name s8.localhost;

    location / {
        proxy_pass http://php8.5-fpm:9001;
    }
}
server {
    listen 80;
    listen [::]:80;
    server_name s7.localhost;

    location / {
        proxy_pass http://php7.2-fpm:9001;
    }
}