server {
    root    /application/yu;
    listen   *:80;
    server_name  yu.localhost;

    #路由匹配
    location / {
        index  index.html index.htm index.php;
    }

    #PHPFPM 监控
    location /phpfpm {
        # #$document_root 的参数是由root行定义
        fastcgi_pass   php8.4-fpm:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $fastcgi_script_name;
    }

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    location ~ \.php$ {
        # #$document_root 的参数是由root行定义
        fastcgi_pass   php8.4-fpm:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param  HTTPS 'on';
        include        fastcgi_params;
    }
}