[program:horizon]
#process_name=%(program_name)s_%(process_num)02d
process_name=%(program_name)s
command=php /application/2026/artisan horizon
autostart=true
autorestart=true
#numprocs=8
user=root
redirect_stderr=true
stdout_logfile=/application/2026/horizon.log
stopwaitsecs=3600
    # /etc/supervisor/conf.d/*.conf