[program:horizon]
process_name=%(program_name)s
command=php /application/2026/artisan horizon
autostart=false
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/application/2026/storage/logs/horizon.log
stopwaitsecs=3600