[program:hyperf-production]
directory=/application/hyperf/
command=php /application/hyperf/bin/hyperf.php start
user=www-data
autostart=false
autorestart=true
stderr_logfile=/application/hyperf/runtime/stderr.log
stdout_logfile=/application/hyperf/runtime/stdout.log