[program:hyperf]
directory=/application/hyperf/
command=php /application/hyperf/bin/hyperf.php server:watch
user=root
autostart=false
autorestart=true
startsecs=1
stderr_logfile=/application/hyperf/runtime/stderr.log
stdout_logfile=/application/hyperf/runtime/stdout.log