[program:octane]
directory=/application/2026
command=php -d variables_order=EGPCS /application/2026/artisan octane:start --server=swoole --host=0.0.0.0 --port=8010
user=root
autostart=false
autorestart=true
startsecs=5
stopwaitsecs=60
stopsignal=TERM
stdout_logfile=/application/2026/storage/logs/octane_out.log
stderr_logfile=/application/2026/storage/logs/octane_err.log