<?php
/**
 * link: http://www.zjhejiang.com/
 * copyright: Copyright (c) 2020 浙江禾匠信息科技有限公司
 * author: xay
 */

namespace yu\wrappers;

class customize extends \php_user_filter
{
    /**
     * $param resource $in 流来的桶队列
     * $param resource $out 流走的桶队列
     * $param int $consumed 处理的字节数
     * $param bool $closing 是流中最后一个桶队列吗？
     */
    public function filter($in, $out, &$consumed, $closing)
    {
        // 迭代桶队列中的每个桶
        while ($bucket = stream_bucket_make_writeable($in)) {
            // 审查桶对象中的脏字
            $bucket->data = str_replace(['a', 'aa', 'aaa'], ['*', '**', '***'], $bucket->data);
            //增加已处理的数据量
            $consumed += $bucket->datalen;
            //把桶放入流向下游的队列中
            stream_bucket_append($out, $bucket);
        }
        return PSFS_PASS_ON; //表示成功
    }

    public function onClose()
    {
        parent::onClose(); // TODO: Change the autogenerated stub
    }

    public function onCreate()
    {
        parent::onCreate(); // TODO: Change the autogenerated stub
    }
}